### PR TITLE
Prepare release of v4.1.5

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Review by devoncarew — COMMENTED** [review]
It looks like we have commits that have not yet rolled through the sdk + google3 (the last vetted commit is af7d8d0881d3309fe9ffc3f0778b33ae745fddd1).

**Comment by kevmoo** [comment]
@devoncarew – we really need a bot for this!

**Comment by kevmoo** [comment]
https://github.com/dart-lang/sse/commit/2830dc9410274d1b215d02d2bb096908caadfa5f is the only new commit...and we KNOW we're testing against the latest pkg:web internally

but okay to wait

Just want to unblock devtools

**Comment by kevmoo** [comment]
Waiting for https://dart-review.googlesource.com/c/sdk/+/353581 to roll to the SDK and get some internal sanity checks

**Comment by kevmoo** [comment]
@devoncarew – we okay to merge and publish?

**Review by devoncarew — APPROVED** [review]
👍

**Pull request merged**
